apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
apiServerExtraArgs:
  feature-gates: RunAsGroup=true
controllerManagerExtraArgs:
  feature-gates: RunAsGroup=true
schedulerExtraArgs:
  feature-gates: RunAsGroup=true
